/* 
 * This file is part of the OSDI component of NGSPICE.
 * Copyright© 2022 SemiMod GmbH.
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. 
 *
 * Author: Pascal Kuthe <pascal.kuthe@semimod.de>
 */

#include "ngspice/iferrmsg.h"
#include "ngspice/klu.h"
#include "ngspice/memory.h"
#include "ngspice/ngspice.h"
#include "ngspice/typedefs.h"

#include "osdi.h"
#include "osdidefs.h"

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/*
 * Handles any errors raised by the setup_instance and setup_model functions
 */
static int handle_init_info(OsdiInitInfo info, const OsdiDescriptor *descr) {
  if (info.flags & (EVAL_RET_FLAG_FATAL | EVAL_RET_FLAG_FINISH)) {
    /* Enhancement-56: a Verilog-A $fatal/$finish during setup is the model
     * rejecting its parameters/configuration (the model's own message was
     * already printed via the log callback). Say so instead of surfacing
     * E_PANIC's baffling "impossible error - can't occur". */
    errMsg = tprintf("a Verilog-A device rejected its configuration during "
                     "setup (%s raised)",
                     (info.flags & EVAL_RET_FLAG_FATAL) ? "$fatal" : "$finish");
    return (E_PRIVATE);
  }

  if (info.num_errors == 0) {
    return (OK);
  }

  for (uint32_t i = 0; i < info.num_errors; i++) {
    OsdiInitError *err = &info.errors[i];
    switch (err->code) {
    case INIT_ERR_OUT_OF_BOUNDS: {
      char *param = descr->param_opvar[err->payload.parameter_id].name[0];
      printf("Parameter %s is out of bounds!\n", param);
      break;
    }
    default:
      printf("Unknown OSDO init error code %d!\n", err->code);
    }
  }
  errMsg = tprintf("%i errors occurred during initialization", info.num_errors);
  return (E_PRIVATE);
}

/*
 * The OSDI instance data contains the `node_mapping` array.
 * Here an index is stored for each node. This function initializes this array
 * with its indicies {0, 1, 2, 3, .., n}.
 * The node collapsing information generated by setup_instance is used to
 * replace these initial indicies with those that a node is collapsed into.
 * For example collapsing nodes i and j sets node_mapping[i] = j.
 *
 * Terminals can never be collapsed in ngspice because they are allocated by
 * ngspice instead of OSDI. Therefore any node collapsing that involves nodes
 * `i < connected_terminals` is ignored.
 *
 * @param const OsdiDescriptor *descr The OSDI descriptor
 * @param void *inst The instance data connected_terminals
 * @param uint32_t connected_terminals The number of terminals that are not
 * internal nodes.
 *
 * @returns The number of nodes required after collapsing.
 * */
static uint32_t collapse_nodes(const OsdiDescriptor *descr, void *inst,
                               uint32_t connected_terminals) {
  /* access data inside instance */
  uint32_t *node_mapping =
      (uint32_t *)(((char *)inst) + descr->node_mapping_offset);
  bool *collapsed = (bool *)(((char *)inst) + descr->collapsed_offset);

  /* without collapsing just return the total number of nodes */
  uint32_t num_nodes = descr->num_nodes;

  /*  populate nodes with themselves*/
  for (uint32_t i = 0; i < descr->num_nodes; i++) {
    node_mapping[i] = i;
  }

  for (uint32_t i = 0; i < descr->num_collapsible; i++) {
    /* check if the collapse hint (V(x,y) <+ 0) was executed */
    if (!collapsed[i]) {
      continue;
    }

    uint32_t from = descr->collapsible[i].node_1;
    uint32_t to = descr->collapsible[i].node_2;

    /* terminals created by the simulator cannot be collapsed
     */
    if (node_mapping[from] < connected_terminals &&
        (to == UINT32_MAX || node_mapping[to] < connected_terminals ||
         node_mapping[to] == UINT32_MAX)) {
      continue;
    }
    /* ensure that to is always the smaller node */
    if (to != UINT32_MAX && node_mapping[from] < node_mapping[to]) {
      uint32_t temp = from;
      from = to;
      to = temp;
    }

    from = node_mapping[from];
    if (to != UINT32_MAX) {
      to = node_mapping[to];
    }

    /* replace nodes mapped to from with to and reduce the number of nodes */
    for (uint32_t j = 0; j < descr->num_nodes; j++) {
      if (node_mapping[j] == from) {
        node_mapping[j] = to;
      } else if (node_mapping[j] > from && node_mapping[j] != UINT32_MAX) {
        node_mapping[j] -= 1;
      }
    }
    num_nodes -= 1;
  }
  return num_nodes;
}

/* replace node mapping local to the current instance (created by
 * collapse_nodes) with global node indicies allocated with CKTmkVolt */
static void write_node_mapping(const OsdiDescriptor *descr, void *inst,
                               uint32_t *nodes) {
  uint32_t *node_mapping =
      (uint32_t *)(((char *)inst) + descr->node_mapping_offset);
  for (uint32_t i = 0; i < descr->num_nodes; i++) {
    if (node_mapping[i] == UINT32_MAX) {
      /* gnd node */
      node_mapping[i] = 0;
    } else {
      node_mapping[i] = nodes[node_mapping[i]];
    }
  }
}

/* NGSPICE state vectors for an instance are always continous so we just write
 * state_start .. state_start + num_state to state_idx */
static void write_state_ids(const OsdiDescriptor *descr, void *inst,
                            uint32_t state_start) {
  uint32_t *state_idx = (uint32_t *)(((char *)inst) + descr->state_idx_off);
  for (uint32_t i = 0; i < descr->num_states; i++) {
    state_idx[i] = state_start + i;
  }
}

static int init_matrix(SMPmatrix *matrix, const OsdiDescriptor *descr,
                       void *inst) {
  uint32_t *node_mapping =
      (uint32_t *)(((char *)inst) + descr->node_mapping_offset);

  double **jacobian_ptr_resist =
      (double **)(((char *)inst) + descr->jacobian_ptr_resist_offset);

  for (uint32_t i = 0; i < descr->num_jacobian_entries; i++) {
    uint32_t equation = descr->jacobian_entries[i].nodes.node_1;
    uint32_t unknown = descr->jacobian_entries[i].nodes.node_2;
    equation = node_mapping[equation];
    unknown = node_mapping[unknown];
    double *ptr = SMPmakeElt(matrix, (int)equation, (int)unknown);

    if (ptr == NULL) {
      return (E_NOMEM);
    }
    jacobian_ptr_resist[i] = ptr;
    uint32_t react_off = descr->jacobian_entries[i].react_ptr_off;
    // complex number for ac analysis
    if (react_off != UINT32_MAX) {

      double **jacobian_ptr_react = (double **)(((char *)inst) + react_off);
      *jacobian_ptr_react = ptr + 1;
    }
  }
  return (OK);
}

int OSDIsetup(SMPmatrix *matrix, GENmodel *inModel, CKTcircuit *ckt,
              int *states) {
  OsdiInitInfo init_info;
  OsdiNgspiceHandle handle;
  GENmodel *gen_model;
  int res = (OK);
  int error;
  CKTnode *tmp;
  GENinstance *gen_inst;
  int err;

  OsdiRegistryEntry *entry = osdi_reg_entry_model(inModel);
  const OsdiDescriptor *descr = entry->descriptor;
  OsdiSimParas sim_params_ = get_simparams(ckt);
  OsdiSimParas *sim_params = &sim_params_;

  /* setup a temporary buffer */
  uint32_t *node_ids = TMALLOC(uint32_t, descr->num_nodes);

  /* determine the number of states required by each instance */
  int num_states = (int)descr->num_states;
  for (uint32_t i = 0; i < descr->num_nodes; i++) {
    if (descr->nodes[i].react_residual_off != UINT32_MAX) {
      num_states += 2;
    }
  }

  for (gen_model = inModel; gen_model; gen_model = gen_model->GENnextModel) {
    void *model = osdi_model_data(gen_model);

    /* setup model parameter (setup_model)*/
    handle = (OsdiNgspiceHandle){.kind = 1, .name = gen_model->GENmodName};
    descr->setup_model((void *)&handle, model, sim_params, &init_info);
    res = handle_init_info(init_info, descr);
    if (res) {
      errRtn = "OSDI setup_model";
      continue;
    }

    for (gen_inst = gen_model->GENinstances; gen_inst;
         gen_inst = gen_inst->GENnextInstance) {
      void *inst = osdi_instance_data(entry, gen_inst);

      /* special handling for temperature parameters */
      double temp = ckt->CKTtemp;
      OsdiExtraInstData *extra_inst_data =
          osdi_extra_instance_data(entry, gen_inst);
      /* Enhancement-394: `temp` OVERRIDES, it does not stack with `dtemp`.
       * Every built-in works that way -- restemp.c forces `RESdtemp = 0` when
       * `temp` is given and warns that dtemp is ignored, and diotemp.c only
       * adds dtemp when temp was NOT given. Adding them here made
       * `temp=75 dtemp=10` mean 85, which is neither device's meaning.
       * (`extra_inst_data->temp` is now Kelvin -- converted in osdiparam.c.) */
      if (extra_inst_data->temp_given) {
        temp = extra_inst_data->temp;
        if (extra_inst_data->dt_given &&
            !(ckt->CKTcurJob && ckt->CKTcurJob->JOBtype == 9)) {
          /* same message and the same sensitivity-analysis silence as
           * restemp.c, so mixed netlists report this one way */
          printf("%s: Instance temperature specified, dtemp ignored\n",
                 gen_inst->GENname);
        }
        /* Enhancement-397: restemp.c does not merely SAY dtemp is ignored, it
         * forces `RESdtemp = 0`. That was invisible until `dtemp` became
         * readable; now that `@n1[dtemp]` answers, leaving the written value in
         * place would report an offset that has no effect on the device -- the
         * exact kind of silent inconsistency this pair of releases exists to
         * remove. Clear it so what is reported is what is used. */
        extra_inst_data->dt = 0.0;
        extra_inst_data->dt_given = false;
      } else if (extra_inst_data->dt_given) {
        temp += extra_inst_data->dt;
      }
      extra_inst_data->has_evaluated = false;

      /* find number of connected ports to allow evaluation of $port_connected
       * and to handle node collapsing correctly later
       * */
      int *terminals = (int *)(gen_inst + 1);
      uint32_t connected_terminals = descr->num_terminals;
      for (uint32_t i = 0; i < descr->num_terminals; i++) {
        if (terminals[i] == -1) {
          connected_terminals = i;
          break;
        }
      }

      /* calculate op independent data, init instance parameters and determine
       which collapsing occurs*/
      handle = (OsdiNgspiceHandle){.kind = 2, .name = gen_inst->GENname};
      descr->setup_instance((void *)&handle, inst, model, temp,
                            connected_terminals, sim_params, &init_info);
      res = handle_init_info(init_info, descr);
      if (res) {
        errRtn = "OSDI setup_instance";
        continue;
      }

      /* setup the instance nodes */

      uint32_t num_nodes = collapse_nodes(descr, inst, connected_terminals);
      /* copy terminals */
      memcpy(node_ids, gen_inst + 1, sizeof(int) * connected_terminals);
      /* Enhancement-45: a terminal net with a nodeset initializer
       * (`electrical a = 5.0;`) nodesets the connected circuit node --
       * unless the netlist already gave one (.nodeset wins). */
      for (uint32_t i = 0; i < connected_terminals; i++) {
        if (!isnan(descr->nodes[i].nodeset)) {
          CKTnode *term = CKTnum2nod(ckt, (int)node_ids[i]);
          if (term && term->number != 0 && !term->nsGiven) {
            term->nodeset = descr->nodes[i].nodeset;
            term->nsGiven = 1;
          }
        }
      }
      /* Enhancement-116: an internal node that appears in NO Jacobian entry is
       * structurally decoupled from the matrix -- e.g. an explicit `ground gnd`
       * net whose branch contributions drop its column (OpenVAF omits the
       * partial w.r.t. a ground reference). Giving it its own solver row leaves
       * an all-zero row/column: Sparse tolerates that decoupled row, but KLU's
       * factorization sees a structurally singular matrix and returns a wrong DC
       * solution. Tie such nodes to ground (node 0) instead of allocating a row;
       * this is consistent with how OpenVAF already treats them (no coupling)
       * and fixes both solvers. Build the "used" set over local node indices. */
      uint32_t *node_mapping =
          (uint32_t *)(((char *)inst) + descr->node_mapping_offset);
      bool *node_used = TMALLOC(bool, num_nodes);
      for (uint32_t i = 0; i < num_nodes; i++)
        node_used[i] = false;
      for (uint32_t e = 0; e < descr->num_jacobian_entries; e++) {
        uint32_t eq = node_mapping[descr->jacobian_entries[e].nodes.node_1];
        uint32_t un = node_mapping[descr->jacobian_entries[e].nodes.node_2];
        if (eq != UINT32_MAX && eq < num_nodes)
          node_used[eq] = true;
        if (un != UINT32_MAX && un < num_nodes)
          node_used[un] = true;
      }
      /* Enhancement-351: reuse the internal nodes if this instance already has
       * them. `sens` calls DEVsetup() a second time on a circuit that is still
       * set up, purely to stamp the perturbation matrix, and requires that no
       * node be allocated -- so allocating a fresh set here is what made every
       * internal-node OSDI model abort the process. The node numbers only
       * survive while the nodes do: OSDIunsetup() deletes them and clears this,
       * so a real re-setup still allocates. Reuse only when the node count
       * matches, since collapsing depends on parameters that `alter` can move. */
      bool reuse_nodes = (extra_inst_data->int_node_ids != NULL &&
                          extra_inst_data->int_node_count == num_nodes);
      if (!reuse_nodes && extra_inst_data->int_node_ids != NULL) {
        FREE(extra_inst_data->int_node_ids);
        extra_inst_data->int_node_ids = NULL;
        extra_inst_data->int_node_count = 0;
      }

      /* create internal nodes as required */
      for (uint32_t i = connected_terminals; i < num_nodes; i++) {
        if (!node_used[i]) {
          /* decoupled internal node -> ground */
          node_ids[i] = 0;
          continue;
        }
        if (reuse_nodes) {
          node_ids[i] = extra_inst_data->int_node_ids[i];
          continue;
        }
        // TODO handle currents  correctly
        if (descr->nodes[i].is_flow) {
          error = CKTmkCur(ckt, &tmp, gen_inst->GENname, descr->nodes[i].name);
        } else {
          error = CKTmkVolt(ckt, &tmp, gen_inst->GENname, descr->nodes[i].name);
        }
        if (error) {
          FREE(node_used);
          return (error);
        }
        node_ids[i] = (uint32_t)tmp->number;
        /* Enhancement-45: apply the net's nodeset initializer as the
         * internal node's .nodeset-equivalent initial guess */
        if (!isnan(descr->nodes[i].nodeset) && !descr->nodes[i].is_flow) {
          tmp->nodeset = descr->nodes[i].nodeset;
          tmp->nsGiven = 1;
        }
      }
      /* remember them for the next DEVsetup() on this same set-up circuit */
      if (!reuse_nodes) {
        extra_inst_data->int_node_ids = TMALLOC(uint32_t, num_nodes);
        if (extra_inst_data->int_node_ids) {
          extra_inst_data->int_node_count = num_nodes;
          for (uint32_t i = 0; i < num_nodes; i++)
            extra_inst_data->int_node_ids[i] = node_ids[i];
        }
      }
      FREE(node_used);
      write_node_mapping(descr, inst, node_ids);

      /* now that we have the node mapping we can create the matrix entries */
      err = init_matrix(matrix, descr, inst);
      if (err) {
        return err;
      }

      /* Allocate extra matrix entries and waveform history for absdelay */
      if (entry->num_absdelays > 0) {
        uint32_t *node_mapping =
            (uint32_t *)(((char *)inst) + descr->node_mapping_offset);
        OsdiExtraInstData *extra =
            osdi_extra_instance_data(entry, gen_inst);
        uint32_t n = entry->num_absdelays;
        const OsdiAbsDelayInfo *infos = (const OsdiAbsDelayInfo *)entry->absdelay_infos;

        extra->delay_jac_y = TMALLOC(double *, n);
        extra->delay_jac_z = TMALLOC(double *, n);
        extra->delay_jac_y_csc = TMALLOC(double *, n);
        extra->delay_jac_z_csc = TMALLOC(double *, n);
        extra->delay_jac_y_cx = TMALLOC(double *, n);
        extra->delay_jac_z_cx = TMALLOC(double *, n);
        extra->delay_hist  = TMALLOC(double *, n);
        extra->delay_hist_cap = 0;

        for (uint32_t k = 0; k < n; k++) {
          int y_spice = (int)node_mapping[infos[k].y_node];
          int z_spice = (int)node_mapping[infos[k].z_node];
          extra->delay_jac_y[k] = SMPmakeElt(matrix, z_spice, y_spice);
          extra->delay_jac_z[k] = SMPmakeElt(matrix, z_spice, z_spice);
          extra->delay_jac_y_csc[k] = NULL;
          extra->delay_jac_z_csc[k] = NULL;
          extra->delay_jac_y_cx[k]  = NULL;
          extra->delay_jac_z_cx[k]  = NULL;
          extra->delay_hist[k]  = NULL;
          if (!extra->delay_jac_y[k] || !extra->delay_jac_z[k])
            return E_NOMEM;
        }
      }

      /* Allocate extra matrix entry and waveform history for last_crossing */
      if (entry->num_last_crossings > 0) {
        uint32_t *node_mapping =
            (uint32_t *)(((char *)inst) + descr->node_mapping_offset);
        OsdiExtraInstData *extra =
            osdi_extra_instance_data(entry, gen_inst);
        uint32_t n = entry->num_last_crossings;
        const OsdiLastCrossingInfo *infos =
            (const OsdiLastCrossingInfo *)entry->last_crossing_infos;

        extra->crossing_jac_z = TMALLOC(double *, n);
        extra->crossing_jac_z_csc = TMALLOC(double *, n);
        extra->crossing_jac_z_cx = TMALLOC(double *, n);
        extra->crossing_hist = TMALLOC(double *, n);
        extra->crossing_hist_cap = 0;
        extra->crossing_time = TMALLOC(double, n);

        for (uint32_t k = 0; k < n; k++) {
          int z_spice = (int)node_mapping[infos[k].z_node];
          extra->crossing_jac_z[k] = SMPmakeElt(matrix, z_spice, z_spice);
          extra->crossing_jac_z_csc[k] = NULL;
          extra->crossing_jac_z_cx[k] = NULL;
          extra->crossing_hist[k] = NULL;
          extra->crossing_time[k] = 0.0;
          if (!extra->crossing_jac_z[k])
            return E_NOMEM;
        }
      }

      /* reserve space in the state vector*/
      gen_inst->GENstate = *states;
      write_state_ids(descr, inst, (uint32_t)*states);
      *states += num_states;
    }
  }

  free(node_ids);

  return res;
}

/* OSDI does not differentiate between setup and temperature update so we just
 * call the setup routines again and assume that  node collapsing (and therefore
 * node mapping) stays the same
 */
extern int OSDItemp(GENmodel *inModel, CKTcircuit *ckt) {
  OsdiInitInfo init_info;
  OsdiNgspiceHandle handle;
  GENmodel *gen_model;
  int res = (OK);
  GENinstance *gen_inst;

  OsdiRegistryEntry *entry = osdi_reg_entry_model(inModel);
  const OsdiDescriptor *descr = entry->descriptor;

  OsdiSimParas sim_params_ = get_simparams(ckt);
  OsdiSimParas *sim_params = &sim_params_;

  for (gen_model = inModel; gen_model != NULL;
       gen_model = gen_model->GENnextModel) {
    void *model = osdi_model_data(gen_model);

    handle = (OsdiNgspiceHandle){.kind = 4, .name = gen_model->GENmodName};
    descr->setup_model((void *)&handle, model, sim_params, &init_info);
    res = handle_init_info(init_info, descr);
    if (res) {
      errRtn = "OSDI setup_model (OSDItemp)";
      continue;
    }

    for (gen_inst = gen_model->GENinstances; gen_inst != NULL;
         gen_inst = gen_inst->GENnextInstance) {
      void *inst = osdi_instance_data(entry, gen_inst);

      // special handleing for temperature parameters
      double temp = ckt->CKTtemp;
      OsdiExtraInstData *extra_inst_data =
          osdi_extra_instance_data(entry, gen_inst);
      /* Enhancement-394: `temp` OVERRIDES, it does not stack with `dtemp`.
       * Every built-in works that way -- restemp.c forces `RESdtemp = 0` when
       * `temp` is given and warns that dtemp is ignored, and diotemp.c only
       * adds dtemp when temp was NOT given. Adding them here made
       * `temp=75 dtemp=10` mean 85, which is neither device's meaning.
       * (`extra_inst_data->temp` is now Kelvin -- converted in osdiparam.c.) */
      if (extra_inst_data->temp_given) {
        temp = extra_inst_data->temp;
        if (extra_inst_data->dt_given &&
            !(ckt->CKTcurJob && ckt->CKTcurJob->JOBtype == 9)) {
          /* same message and the same sensitivity-analysis silence as
           * restemp.c, so mixed netlists report this one way */
          printf("%s: Instance temperature specified, dtemp ignored\n",
                 gen_inst->GENname);
        }
        /* Enhancement-397: restemp.c does not merely SAY dtemp is ignored, it
         * forces `RESdtemp = 0`. That was invisible until `dtemp` became
         * readable; now that `@n1[dtemp]` answers, leaving the written value in
         * place would report an offset that has no effect on the device -- the
         * exact kind of silent inconsistency this pair of releases exists to
         * remove. Clear it so what is reported is what is used. */
        extra_inst_data->dt = 0.0;
        extra_inst_data->dt_given = false;
      } else if (extra_inst_data->dt_given) {
        temp += extra_inst_data->dt;
      }
      extra_inst_data->has_evaluated = false;

      handle = (OsdiNgspiceHandle){.kind = 2, .name = gen_inst->GENname};
      /* find number of connected ports to allow evaluation of $port_connected
       * and to handle node collapsing correctly later
       * */
      int *terminals = (int *)(gen_inst + 1);
      uint32_t connected_terminals = descr->num_terminals;
      for (uint32_t i = 0; i < descr->num_terminals; i++) {
        if (terminals[i] == -1) {
          connected_terminals = i;
          break;
        }
      }

      descr->setup_instance((void *)&handle, inst, model, temp,
                            connected_terminals, sim_params, &init_info);
      res = handle_init_info(init_info, descr);
      if (res) {
        errRtn = "OSDI setup_instance (OSDItemp)";
        continue;
      }
      // TODO check that there are no changes in node collapse?
    }
  }
  return res;
}

/* delete internal nodes
 */
extern int OSDIunsetup(GENmodel *inModel, CKTcircuit *ckt) {
  GENmodel *gen_model;
  GENinstance *gen_inst;
  int num;

  OsdiRegistryEntry *entry = osdi_reg_entry_model(inModel);
  const OsdiDescriptor *descr = entry->descriptor;

  for (gen_model = inModel; gen_model != NULL;
       gen_model = gen_model->GENnextModel) {

    for (gen_inst = gen_model->GENinstances; gen_inst != NULL;
         gen_inst = gen_inst->GENnextInstance) {
      void *inst = osdi_instance_data(entry, gen_inst);

      /* Enhancement-351: the internal nodes recorded at setup are about to be
       * deleted below, so drop the record with them -- the next setup must
       * allocate afresh rather than hand out numbers that no longer exist.
       * This is the OSDI counterpart of INDunsetup() zeroing INDbrEq. */
      {
        OsdiExtraInstData *extra = osdi_extra_instance_data(entry, gen_inst);
        if (extra->int_node_ids) {
          FREE(extra->int_node_ids);
          extra->int_node_ids = NULL;
        }
        extra->int_node_count = 0;
        /* Enhancement-364: release this instance's transient-noise generators;
           the next run re-probes the circuit and re-allocates. */
        osdi_trnoise_free(extra);
        osdi_trnoise_reset();
      }

      // reset is collapsible
      bool *collapsed = (bool *)(((char *)inst) + descr->collapsed_offset);
      memset(collapsed, 0, sizeof(bool) * descr->num_collapsible);

      uint32_t *node_mapping =
          (uint32_t *)(((char *)inst) + descr->node_mapping_offset);
      for (uint32_t i = 0; i < descr->num_nodes; i++) {
        num = (int)node_mapping[i];
        // hand coded implementations just know which nodes were collapsed
        // however nodes may be collapsed multiple times so we can't easily use
        // an approach like that instead we delete all nodes
        // Deleting twiche with CKLdltNNum is fine (entry is already removed
        // from the linked list and therefore no action is taken).
        // However CKTdltNNum (rightfully) throws an error when trying to delete
        // an external node. Therefore we need to check for each node that it is
        // an internal node
        if (ckt->prev_CKTlastNode->number &&
            num > ckt->prev_CKTlastNode->number) {
          CKTdltNNum(ckt, num);
        }
      }
    }
  }
  return (OK);
}
#ifdef KLU
#include "ngspice/klu-binding.h"
static int init_matrix_klu(SMPmatrix *matrix, const OsdiDescriptor *descr,
                           void *inst, double **inst_matrix_ptrs) {
  BindElement tmp;
  BindElement *matched;
  BindElement *bindings = matrix->SMPkluMatrix->KLUmatrixBindStructCOO;
  size_t nz = (size_t)matrix->SMPkluMatrix->KLUmatrixLinkedListNZ;
  uint32_t *node_mapping =
      (uint32_t *)(((char *)inst) + descr->node_mapping_offset);
  double **jacobian_ptr_resist =
      (double **)(((char *)inst) + descr->jacobian_ptr_resist_offset);

  for (uint32_t i = 0; i < descr->num_jacobian_entries; i++) {
    uint32_t equation = descr->jacobian_entries[i].nodes.node_1;
    uint32_t unknown = descr->jacobian_entries[i].nodes.node_2;
    equation = node_mapping[equation];
    unknown = node_mapping[unknown];
    if (equation != 0 && unknown != 0) {
      tmp.COO = jacobian_ptr_resist[i];
      tmp.CSC = NULL;
      tmp.CSC_Complex = NULL;
      matched = (BindElement *)bsearch(&tmp, bindings, nz, sizeof(BindElement),
                                       BindCompare);
      if (matched == NULL) {
        printf("Ptr %p not found in BindStruct Table\n",
               jacobian_ptr_resist[i]);
        return (E_PANIC);
      }
      uint32_t react_off = descr->jacobian_entries[i].react_ptr_off;
      // complex number for ac analysis
      if (react_off != UINT32_MAX) {
        double **jacobian_ptr_react = (double **)(((char *)inst) + react_off);
        *jacobian_ptr_react = matched->CSC_Complex + 1;
      }
      jacobian_ptr_resist[i] = matched->CSC;
      inst_matrix_ptrs[2 * i] = matched->CSC;
      inst_matrix_ptrs[2 * i + 1] = matched->CSC_Complex;
    }
  }
  return (OK);
}

static int update_matrix_klu(const OsdiDescriptor *descr, void *inst,
                             double **inst_matrix_ptrs, bool complex) {
  uint32_t *node_mapping =
      (uint32_t *)(((char *)inst) + descr->node_mapping_offset);
  double **jacobian_ptr_resist =
      (double **)(((char *)inst) + descr->jacobian_ptr_resist_offset);

  for (uint32_t i = 0; i < descr->num_jacobian_entries; i++) {
    uint32_t equation = descr->jacobian_entries[i].nodes.node_1;
    uint32_t unknown = descr->jacobian_entries[i].nodes.node_2;
    equation = node_mapping[equation];
    unknown = node_mapping[unknown];
    if (equation != 0 && unknown != 0) {
      jacobian_ptr_resist[i] = inst_matrix_ptrs[2 * i + complex];
    }
  }
  return (OK);
}

int OSDIbindCSC(GENmodel *inModel, CKTcircuit *ckt) {

  OsdiRegistryEntry *entry = osdi_reg_entry_model(inModel);
  const OsdiDescriptor *descr = entry->descriptor;
  GENmodel *gen_model;
  GENinstance *gen_inst;

  /* setup a temporary buffer
  uint32_t *node_ids = TMALLOC(uint32_t, descr->num_nodes);*/

  BindElement *bindings = ckt->CKTmatrix->SMPkluMatrix->KLUmatrixBindStructCOO;
  size_t nz = (size_t)ckt->CKTmatrix->SMPkluMatrix->KLUmatrixLinkedListNZ;

  for (gen_model = inModel; gen_model; gen_model = gen_model->GENnextModel) {
    /* void *model = osdi_model_data(gen_model); unused */
    for (gen_inst = gen_model->GENinstances; gen_inst;
         gen_inst = gen_inst->GENnextInstance) {
      void *inst = osdi_instance_data(entry, gen_inst);
      double **matrix_ptrs = osdi_instance_matrix_ptr(entry, gen_inst);
      int err = init_matrix_klu(ckt->CKTmatrix, descr, inst, matrix_ptrs);
      if (err != (OK)) {
        return err;
      }

      /* Rebind absdelay Jacobian pointers from COO to KLU CSC format.
       * init_matrix_klu only handles descr->jacobian_entries; the extra
       * delay_jac_y/z pointers allocated in OSDIsetup still point into the
       * COO buffer and must be rebound here so absdelay_stamp_dc/osdiacld
       * write into the live KLU matrix. */
      if (entry->num_absdelays > 0) {
        OsdiExtraInstData *extra = osdi_extra_instance_data(entry, gen_inst);
        BindElement tmp;
        for (uint32_t k = 0; k < entry->num_absdelays; k++) {
          if (extra->delay_jac_y[k]) {
            tmp.COO = extra->delay_jac_y[k];
            BindElement *m = (BindElement *)bsearch(&tmp, bindings, nz,
                                                    sizeof(BindElement),
                                                    BindCompare);
            if (m) {
              extra->delay_jac_y_csc[k] = m->CSC;
              extra->delay_jac_y_cx[k]  = m->CSC_Complex;
              extra->delay_jac_y[k]     = m->CSC;
            }
          }
          if (extra->delay_jac_z[k]) {
            tmp.COO = extra->delay_jac_z[k];
            BindElement *m = (BindElement *)bsearch(&tmp, bindings, nz,
                                                    sizeof(BindElement),
                                                    BindCompare);
            if (m) {
              extra->delay_jac_z_csc[k] = m->CSC;
              extra->delay_jac_z_cx[k]  = m->CSC_Complex;
              extra->delay_jac_z[k]     = m->CSC;
            }
          }
        }
      }

      /* Same rebinding for last_crossing's single z-row diagonal entry. */
      if (entry->num_last_crossings > 0) {
        OsdiExtraInstData *extra = osdi_extra_instance_data(entry, gen_inst);
        BindElement tmp;
        for (uint32_t k = 0; k < entry->num_last_crossings; k++) {
          if (extra->crossing_jac_z[k]) {
            tmp.COO = extra->crossing_jac_z[k];
            BindElement *m = (BindElement *)bsearch(&tmp, bindings, nz,
                                                    sizeof(BindElement),
                                                    BindCompare);
            if (m) {
              extra->crossing_jac_z_csc[k] = m->CSC;
              extra->crossing_jac_z_cx[k]  = m->CSC_Complex;
              extra->crossing_jac_z[k]     = m->CSC;
            }
          }
        }
      }
    }
  }

  return (OK);
}
int OSDIupdateCSC(GENmodel *inModel, CKTcircuit *ckt, bool complex) {

  OsdiRegistryEntry *entry = osdi_reg_entry_model(inModel);
  const OsdiDescriptor *descr = entry->descriptor;
  GENmodel *gen_model;
  GENinstance *gen_inst;

  NG_IGNORE(ckt);

  /* setup a temporary buffer 
  uint32_t *node_ids = TMALLOC(uint32_t, descr->num_nodes);*/

  for (gen_model = inModel; gen_model; gen_model = gen_model->GENnextModel) {
    /* void *model = osdi_model_data(gen_model); unused */
    for (gen_inst = gen_model->GENinstances; gen_inst;
         gen_inst = gen_inst->GENnextInstance) {
      void *inst = osdi_instance_data(entry, gen_inst);
      double **matrix_ptrs = osdi_instance_matrix_ptr(entry, gen_inst);
      int err = update_matrix_klu(descr, inst, matrix_ptrs, complex);
      if (err != (OK)) {
        return err;
      }

      /* Switch the absdelay delay-row pointers between the real (CSC) and
       * complex (CSC_Complex) KLU arrays, mirroring the regular Jacobian.
       * Without this, the AC complex solve would write the delay stamps into
       * the unused real array, leaving the delay rows empty -> singular. */
      if (entry->num_absdelays > 0) {
        OsdiExtraInstData *extra = osdi_extra_instance_data(entry, gen_inst);
        for (uint32_t k = 0; k < entry->num_absdelays; k++) {
          if (extra->delay_jac_y_csc[k])
            extra->delay_jac_y[k] =
                complex ? extra->delay_jac_y_cx[k] : extra->delay_jac_y_csc[k];
          if (extra->delay_jac_z_csc[k])
            extra->delay_jac_z[k] =
                complex ? extra->delay_jac_z_cx[k] : extra->delay_jac_z_csc[k];
        }
      }

      if (entry->num_last_crossings > 0) {
        OsdiExtraInstData *extra = osdi_extra_instance_data(entry, gen_inst);
        for (uint32_t k = 0; k < entry->num_last_crossings; k++) {
          if (extra->crossing_jac_z_csc[k])
            extra->crossing_jac_z[k] =
                complex ? extra->crossing_jac_z_cx[k] : extra->crossing_jac_z_csc[k];
        }
      }
    }
  }

  return (OK);
}
int OSDIbindCSCComplexToReal(GENmodel *inModel, CKTcircuit *ckt) {
  return OSDIupdateCSC(inModel, ckt, false);
}

int OSDIbindCSCComplex(GENmodel *inModel, CKTcircuit *ckt) {
  return OSDIupdateCSC(inModel, ckt, true);
}
#endif
