#!/usr/bin/env python3
"""Regenerate the `help all` table (the last section) of ngspice_commands.md
from a REAL ngspice run, so the document lists every command the build's
`help all` prints, with the one-line description the command table carries.

Usage:  python3 docs/internals/ngspice_internals/make_commands_table.py
        NGSPICE_BIN=/path/to/ngspice python3 ... (to point at another build)

The table sits between the `<!-- helpall:begin -->` and `<!-- helpall:end -->`
markers; everything else in the document is left alone. The helpcmd suite
(examples/helpcmd_examples/verify_helpcmd.py, check [9]) compares the table
with the binary, so a command added without rerunning this script fails it.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
DOC = os.path.join(HERE, "ngspice_commands.md")
BEGIN, END = "<!-- helpall:begin -->", "<!-- helpall:end -->"

NG = os.environ.get("NGSPICE_BIN")
if not NG:
    for cand in (os.path.join(ROOT, "ngspice-46", "build", "src", "ngspice"),
                 os.path.join(ROOT, "bin", "macos", "apple-silicon", "ngspice")):
        if os.path.exists(cand):
            NG = cand
            break
if not NG or not os.path.exists(NG):
    sys.exit("no ngspice binary found; set NGSPICE_BIN")

LINE = re.compile(r"^([a-z_0-9]+)\s(.*?)\s*:\s(.*)$")


def help_all(binary):
    """(name, arguments, description) for every line `help all` prints."""
    r = subprocess.run([binary, "-p"], input="help all\nquit\n", capture_output=True,
                       text=True, timeout=120, errors="replace",
                       env=dict(os.environ, SPICE_NO_DATASEG="1"))
    rows = []
    for line in r.stdout.splitlines():
        m = LINE.match(line)
        if m:
            name, args, desc = m.groups()
            rows.append((name, args.strip(), desc.strip()))
    return rows


def cell(text):
    """A table cell: pipes escaped, and every `@name[...]` accessor put in a code
    span (the repository's mention check reads a bare one as a mention)."""
    text = re.sub(r"(?<!`)(@[A-Za-z_][\w.:]*\[[^\]]*\])(?!`)", r"`\1`", text)
    return text.replace("|", "\\|")


def table(rows):
    out = [f"{len(rows)} commands, alphabetically, as the build's `help all` prints them "
           "(name, arguments, one-line description; regenerated by "
           "`make_commands_table.py`, checked by the helpcmd suite).", "",
           "| Command | Arguments | Description |", "|---|---|---|"]
    for name, args, desc in sorted(rows):
        a = f"`{args.replace('|', chr(92) + '|')}`" if args else ""   # one code span
        out.append(f"| `{name}` | {a} | {cell(desc)} |")
    return "\n".join(out)


def main():
    rows = help_all(NG)
    if len(rows) < 100:
        sys.exit(f"only {len(rows)} commands parsed from {NG}; refusing to rewrite")
    doc = open(DOC).read()
    i, j = doc.find(BEGIN), doc.find(END)
    if i < 0 or j < 0 or j < i:
        sys.exit("markers not found in ngspice_commands.md")
    new = doc[:i + len(BEGIN)] + "\n" + table(rows) + "\n" + doc[j:]
    if new != doc:
        open(DOC, "w").write(new)
    print(f"{len(rows)} commands from {os.path.relpath(NG, ROOT)}; table "
          f"{'rewritten' if new != doc else 'unchanged'}")


if __name__ == "__main__":
    main()
