#!/usr/bin/env python3
"""
verify_noisecorr.py -- verifies correlated noise per the LRM, end-to-end
through the committed openvaf-r + ngspice (E-42 machinery, E-528 semantics).

LRM 4.6.4.6: correlation follows the CALL -- "perfectly correlated noise is
generated by using the output of one noise function for more than one noise
source" -- while two separate calls are uncorrelated even when they share a
name (4.6.4.1 makes the name a REPORTING label whose contributions combine in
the summary). E-42 built the coherent amplitude machinery keyed on the name
string; the E-528 analysis-noise audit moved the correlation key to the
CALL SITE (the compiler exports it after a \x1f separator in the source
name; ngspice correlates on the full string and strips the suffix for the
report), which is what this suite pins.

All checks drive PSD 1e-12 sources through a unity-transfer series chain, so
sqrt-PSD amplitudes are 1e-6 V/sqrt(Hz) each:

  1. ONE call used twice        -> onoise = 2e-6      (coherent; the LRM idiom)
  2. distinct calls             -> onoise = 1.414e-6  (independent)
  3. one call, second use -x    -> onoise = 0         (anti-phase cancellation)
  4. one call, factors 2x + 1x  -> onoise = 3e-6      (amplitude-weighted)
  5. two INSTANCES              -> onoise = 2.828e-6  (instances independent)
  6. white + flicker, one label -> onoise = 1.414e-6  (functions never correlate)
  7. TWO calls sharing a label  -> onoise = 1.414e-6  (label is not correlation)
  8. per-label report: the shared label's vector carries the combined power

Every SPICE deck starts with a title line (SPICE treats line 1 as the title!).
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from _setup import VAF as OPENVAF, NG as NGSPICE
from _setup import check_both_solvers as _check_both_solvers; _check_both_solvers(__file__)  # verify under BOTH KLU and Sparse solvers


def run(deck, *names):
    with open(os.path.join(HERE, "_n.cir"), "w") as fh:
        fh.write(deck)
    out = subprocess.run([NGSPICE, "-b", "_n.cir"], cwd=HERE,
                         capture_output=True, text=True, timeout=120).stdout
    vals = {}
    for line in out.splitlines():
        stripped = line.strip().lower()
        for nm in names:
            if stripped.startswith(nm.lower() + " ") and nm not in vals:
                vals[nm] = float(line.split("=", 1)[1].strip())
    return vals


def noise_deck(model, freq="1k", extra_ctrl="", instances=None):
    instances = instances or ["NDUT out 0 nm"]
    return ("* E-42 noise correlation\n" + "\n".join(instances) + "\n"
            "R1 out 0 1G\nVin in 0 DC 0 AC 1\nR2 in 0 1k\n"
            f".model nm {model}\n"
            ".control\npre_osdi noisecorr_demo.osdi\n"
            f"noise v(out) vin lin 1 {freq} {freq} 1\n"
            "setplot noise1\nprint all\n"
            f"{extra_ctrl}.endc\n.end\n")


def main():
    subprocess.run([OPENVAF, "noisecorr_demo.va", "-o", "noisecorr_demo.osdi"],
                   cwd=HERE, check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    ok = True

    def check(label, got, want, tol=1e-9):
        nonlocal ok
        good = abs(got - want) < tol
        ok = ok and good
        print(f"  {'PASS' if good else 'FAIL'}  {label}   got {got:.6e}, want {want:.6e}")

    print("[1] same-named pair: amplitudes add coherently (was power-summed)")
    v = run(noise_deck("ncorr"), "onoise_spectrum")
    check("onoise = 2e-6", v["onoise_spectrum"], 2e-6, 1e-12)

    print("[2] distinct names stay independent (classic power sum, unchanged)")
    v = run(noise_deck("nuncorr"), "onoise_spectrum")
    check("onoise = sqrt(2)*1e-6", v["onoise_spectrum"], 2**0.5 * 1e-6, 1e-12)

    print("[3] same name, one contribution negated: anti-phase CANCELLATION")
    v = run(noise_deck("nanti"), "onoise_spectrum")
    check("onoise = 0", v["onoise_spectrum"], 0.0, 1e-12)

    print("[4] scaled factors weight the amplitudes linearly: |2 + 1|*1e-6")
    v = run(noise_deck("nscale"), "onoise_spectrum")
    check("onoise = 3e-6", v["onoise_spectrum"], 3e-6, 1e-12)

    print("[5] same name in two INSTANCES: correlation never crosses instances")
    v = run(noise_deck("ncorr", instances=["NDUT1 out mid nm", "NDUT2 mid 0 nm"]),
            "onoise_spectrum")
    check("onoise = sqrt(8e-12)", v["onoise_spectrum"], 8e-12**0.5, 1e-12)

    print("[6] white + flicker under one label: FUNCTIONS never correlate (4.6.4.6)")
    v = run(noise_deck("nmix", freq="1"), "onoise_spectrum")
    check("onoise = sqrt(2)*1e-6 at 1 Hz", v["onoise_spectrum"], 2**0.5 * 1e-6, 1e-12)

    print("[7] two CALLS sharing a label stay uncorrelated (E-528; was coherent 2e-6)")
    v = run(noise_deck("nlabel"), "onoise_spectrum")
    check("onoise = sqrt(2)*1e-6", v["onoise_spectrum"], 2**0.5 * 1e-6, 1e-12)

    print("[8] per-label report: shared label combines in the summary vector")
    v = run(noise_deck("nlabel"), "onoise_ndut_src1", "onoise_ndut")
    check("onoise_ndut_src1 (combined label) = sqrt(2)*1e-6",
          v["onoise_ndut_src1"], 2**0.5 * 1e-6, 1e-12)
    check("onoise_ndut (device total) matches", v["onoise_ndut"], 2**0.5 * 1e-6, 1e-12)

    print("[9] the shared-call device total is the coherent 2e-6")
    v = run(noise_deck("ncorr"), "onoise_ndut", "onoise_spectrum")
    check("onoise_ndut (device total) = 2e-6 density",
          v["onoise_ndut"], 2e-6, 1e-12)

    print()
    print("ALL PASS" if ok else "SOME CHECKS FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
