#!/usr/bin/env python3
"""Design a 5th-order analog Bessel low-pass filter with scipy, emit the
Verilog-A model using laplace_nd with the exact same coefficients, and later
provide the analytical H(jw) for comparison against the ngspice simulation.
"""
import numpy as np
from scipy import signal

N = 5
FC_HZ = 1000.0  # -3dB-ish corner (Bessel's "phase" norm keeps -3dB near here for low order)
WC = 2 * np.pi * FC_HZ

# analog, phase-normalized (scipy default) 5th-order Bessel lowpass.
# b, a returned in *descending* power order (b[0]*s^m + ... ; a[0]*s^n + ...).
b, a = signal.bessel(N, WC, btype="low", analog=True, norm="phase")

NUM_ASC = b[::-1]  # ascending powers of s, as laplace_nd expects
DEN_ASC = a[::-1]

if __name__ == "__main__":
    print(f"fc = {FC_HZ} Hz, wc = {WC:.6e} rad/s")
    print("num (ascending):", NUM_ASC)
    print("den (ascending):", DEN_ASC)
    print("DC gain:", NUM_ASC[0] / DEN_ASC[0])

    def va_array(coeffs):
        # Scientific notation for clarity/precision. (A bare integer-looking
        # literal like "6134876650875544" -- too large for i32 -- used to
        # crash OpenVAF; it's now a graceful float-literal fallback instead,
        # but scientific notation is still the clearer way to write these.)
        return "'{" + ", ".join(f"{float(c):.17e}" for c in coeffs) + "}"

    va = f"""`include "disciplines.vams"

// 5th-order analog Bessel low-pass filter, fc = {FC_HZ:.0f} Hz, realized purely
// via laplace_nd -- no actual RLC network in the model. Coefficients are the
// exact scipy.signal.bessel(N=5, Wn=2*pi*{FC_HZ:.0f}, analog=True, norm='phase')
// output, generated by design_bessel.py (do not hand-edit; regenerate instead).
module bessel5(in, out);
    input in;
    output out;
    electrical in, out;

    analog begin
        V(out) <+ laplace_nd(V(in), {va_array(NUM_ASC)}, {va_array(DEN_ASC)});
    end
endmodule
"""
    with open("bessel5.va", "w") as f:
        f.write(va)
    print("wrote bessel5.va")
