#!/usr/bin/env python3
# generated by ngspice 'pyplot -contour' (Enhancement-218)
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
_here = os.path.dirname(os.path.abspath(__file__))
d = np.loadtxt(os.path.join(_here, 'contour.data'))
if d.ndim == 1:
    d = d.reshape(-1, 3)
x = d[:, 0]; y = d[:, 1]; z = d[:, 2]
fig, ax = plt.subplots(figsize=(7.0, 5.4))
levels = None
try:
    cf = ax.tricontourf(x, y, z, levels=levels, cmap='viridis')
except (RuntimeError, ValueError) as e:
    raise SystemExit('pyplot -contour: cannot triangulate the (x, y) points -- a contour needs a genuine 2-D sweep '
                     '(the points must not be collinear): ' + str(e))
cb = fig.colorbar(cf, ax=ax, pad=0.02)
cb.set_label('v(out)')
ax.set_xlabel('time')
ax.set_ylabel('time')
ax.set_title('* pyplot base')
fig.tight_layout()
fig.savefig(os.path.join(_here, 'contour') + '.png', dpi=110)
print('pyplot: wrote ' + 'contour' + '.png')
