#!/usr/bin/env python3
"""Enhancement-528: analysis phases and noise, audited against Accellera
VAMS-2023 clause 4.6, then fixed.

What this suite pins, each against the quoted clause:

  * 4.6.1 Table 4-22 (TRAN OP column) -- analysis("ic") and
    analysis("static") shall be 1 at the operating point that precedes a
    transient (with "tran" 1 and "dc" 0), and 0 at the timepoints. The
    bits used to ride MODEINITTRAN -- ngspice's FIRST ACCEPTED TIMESTEP
    -- so the 4.6.1 `if (analysis("ic"))` initial-condition idiom fired
    mid-transient instead of at the op.
  * 4.6.2 -- analysis("nodeset") is 1 while the deck's .nodeset values
    are enforced (the flag existed and was never set anywhere).
  * 4.6.3 -- ac_stim "returns zero on all small-signal analyses using
    names which do not match analysis_name": ngspice's .noise reuses the
    AC loader, and the match was against the LITERAL "ac" -- an
    ac_stim("ac") source was injected into the noise gain solve
    (poisoning the input-referred noise 1000x) while ac_stim("noise")
    could never activate. Both now match the RUNNING analysis.
  * 4.6.4.6 -- "perfectly correlated noise is generated by using the
    output of ONE noise function for more than one noise source", while
    separate calls stay uncorrelated even under a shared label; 4.6.4.1
    makes the name a REPORTING label whose contributions combine in the
    summary. E-42's coherent machinery was keyed on the name string; the
    key is the CALL SITE now (exported after a \\x1f separator in the
    OSDI source name; ngspice strips it for the per-label summary
    vectors).
"""

import atexit
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from _setup import NG as NGSPICE  # noqa: E402
from _setup import VAF as OPENVAF  # noqa: E402
from _setup import check_both_solvers  # noqa: E402

check_both_solvers(__file__)


def _cleanup():
    for junk in os.listdir(HERE):
        if junk.startswith("_ln_"):
            try:
                os.remove(os.path.join(HERE, junk))
            except OSError:
                pass


atexit.register(_cleanup)

checks = passed = 0


def check(label, ok, detail=""):
    global checks, passed
    checks += 1
    passed += bool(ok)
    print(f"  {'PASS' if ok else 'FAIL'}  {label}" + (f"  [{detail}]" if detail else ""))


def compile_file(name):
    osdi = os.path.join(HERE, f"_ln_{os.path.splitext(name)[0]}.osdi")
    r = subprocess.run([OPENVAF, os.path.join(HERE, name), "-o", osdi], cwd=HERE,
                       capture_output=True, text=True, timeout=300, errors="replace")
    return r.returncode, (r.stdout + r.stderr), osdi


def run(body, ctl, tag, osdi, timeout=300):
    p = os.path.join(HERE, f"_ln_{tag}.cir")
    with open(p, "w") as f:
        f.write(f"lrmnoise\n{body}\n.control\npre_osdi {os.path.basename(osdi)}\n"
                f"option noacct\n{ctl}\nquit\n.endc\n.end\n")
    try:
        r = subprocess.run([NGSPICE, "-b", os.path.basename(p)], cwd=HERE,
                           capture_output=True, text=True, timeout=timeout,
                           errors="replace")
        return r.stdout + r.stderr
    except subprocess.TimeoutExpired:
        return "[TIMEOUT]"


def num(out, name):
    m = re.search(rf"^{re.escape(name)}\s*=\s*(\S+)", out, re.M)
    try:
        return float(m.group(1)) if m else None
    except ValueError:
        return None


def close(a, b, tol=1e-9):
    return a is not None and abs(a - b) <= tol


# ---- [1] Table 4-22 static phases ------------------------------------------
print("analysis() static phases (LRM Table 4-22):")
rc, out, osdi = compile_file("aprobe.va")
check("aprobe.va compiles", rc == 0)
if rc == 0:
    body = "V1 in 0 DC 1.0\nN1 in 0 mm\n.model mm aprobe"
    sim = run(body, "tran 1u 3u", "tr", osdi)
    t0 = [l for l in sim.splitlines() if "FLAGS t=0 " in l]
    check("the TRAN OP evaluation reports ic=1 static=1 tran=1 dc=0",
          len(t0) >= 1 and "ic=1" in t0[0] and "static=1" in t0[0]
          and "tran=1" in t0[0] and "dc=0" in t0[0],
          t0[0][t0[0].find("dc="):][:44] if t0 else "no t=0 line")
    later = [l for l in sim.splitlines()
             if "FLAGS t=" in l and "FLAGS t=0 " not in l]
    check("...and every t > 0 evaluation reports ic=0 static=0",
          bool(later) and all("ic=0" in l and "static=0" in l for l in later),
          f"{len(later)} timepoint evals")

rc, out, osdi = compile_file("nsl.va")
check("nsl.va (nodeset latch) compiles", rc == 0)
if rc == 0:
    body = "V1 in 0 DC 1\nR1 in out 1k\nN1 out 0 mm\n.model mm nsl"
    sim = run(body + "\n.nodeset v(out)=0.3", "op\nprint @n1[saw]", "ns1", osdi)
    check("analysis(\"nodeset\") is 1 while .nodeset values are enforced",
          close(num(sim, "@n1[saw]"), 1.0), f"{num(sim, '@n1[saw]')}")
    sim = run(body, "op\nprint @n1[saw]", "ns0", osdi)
    check("...and stays 0 without any .nodeset", close(num(sim, "@n1[saw]"), 0.0),
          f"{num(sim, '@n1[saw]')}")

# ---- [2] ac_stim vs the running small-signal analysis (4.6.3) --------------
print("\nac_stim activation (LRM 4.6.3):")
DIV = ("vin in 0 dc 0 ac 1\nr1 in outp 1k\nr2 outp 0 1k\nN1 outp {model}\n"
       ".model {model} {model}")
CTL = "noise v(outp) vin lin 1 1000 1000\nsetplot noise1\nprint inoise_spectrum"
control = None
for name in ("acsi", "acsn"):
    rc, out, osdi = compile_file(f"{name}.va")
    check(f"{name}.va compiles", rc == 0)
rc, out, osdi_i = compile_file("acsi.va")
rc, out, osdi_n = compile_file("acsn.va")
sim_ctl = run("vin in 0 dc 0 ac 1\nr1 in outp 1k\nr2 outp 0 1k", CTL, "actl", osdi_i)
ctl_v = num(sim_ctl, "inoise_spectrum")
sim = run(DIV.format(model="macsi"), CTL, "aci", osdi_i)
check("an \"ac\"-named stimulus stays OUT of the .noise gain solve "
      "(it used to poison inoise 1000x)",
      close(num(sim, "inoise_spectrum"), ctl_v, abs(ctl_v) * 1e-6),
      f"{num(sim, 'inoise_spectrum')} vs control {ctl_v}")
sim = run(DIV.format(model="macsn"), CTL, "acn", osdi_n)
check("ac_stim(\"noise\") PARTICIPATES in the noise gain solve "
      "(it could never activate)",
      num(sim, "inoise_spectrum") is not None
      and abs(num(sim, "inoise_spectrum") - ctl_v) > abs(ctl_v) * 0.5,
      f"{num(sim, 'inoise_spectrum')}")

# ---- [3] correlation per call site (4.6.4.6 / 4.6.4.1) ---------------------
print("\nnoise correlation follows the CALL (LRM 4.6.4.6):")
NDECK = "V1 a 0 dc 0 ac 1\nRs a x 1\nN1 x 0 mm\nRl x 0 1G\n.model mm {m}"
NCTL = "noise v(x) V1 lin 1 1k 1k\nsetplot noise1\nprint onoise_spectrum"
for m, want, why in [
    ("ncorrA", 0.0, "ONE call routed into both contributions cancels exactly"),
    ("ncorrB", 2**0.5 * 1e-6, "two calls sharing a label stay UNCORRELATED "
                              "(they cancelled to 0 before)"),
    ("ncorrC", 2**0.5 * 1e-6, "distinct labels independent"),
]:
    rc, out, osdi = compile_file(f"{m}.va")
    sim = run(NDECK.format(m=m), NCTL, m, osdi)
    check(f"{why}: onoise = {want:g}",
          close(num(sim, "onoise_spectrum"), want, 1e-11),
          f"{num(sim, 'onoise_spectrum')}")

rc, out, osdi = compile_file("nrep.va")
check("nrep.va compiles", rc == 0)
if rc == 0:
    body = ("V1 in 0 DC 0 AC 1\nR0 in 0 1k\nN1 a 0 mm\n.model mm nrep\nR1 a 0 1k")
    sim = run(body, "noise v(a) V1 lin 1 1k 1k 1\nsetplot noise1\n"
              "print onoise_n1_shot onoise_n1_th onoise_n1", "rep", osdi)
    check("the shared label's summary vector carries the COMBINED power "
          "(1e-18 + 3e-18 through 500 ohm)",
          close(num(sim, "onoise_n1_shot"), 1e-6, 1e-9),
          f"{num(sim, 'onoise_n1_shot')}")
    check("the distinct label reports alone", close(num(sim, "onoise_n1_th"),
          (5e-18 * 250000) ** 0.5, 1e-9), f"{num(sim, 'onoise_n1_th')}")
    check("the device total matches", close(num(sim, "onoise_n1"),
          (9e-18 * 250000) ** 0.5, 1e-9), f"{num(sim, 'onoise_n1')}")

# ---- [4] noise and ac_stim on a SWITCH BRANCH (round-4 audit) --------------
# LRM 5.6.5 / 5.6.1.3 / 4.6.4 / 6.3.6. A switch branch carries its branch
# current as an unknown, so both arms' sources inject into that equation --
# which is where both defects lived. Every value below is the PLAIN branch's,
# measured on the same circuit: the switch branch must not differ.
print("\nnoise on a switch branch (LRM 5.6.5 + 6.3.6):")
SWDECK = "V1 a 0 dc 0 ac 1\nR1 a x 1k\nN1 x 0 mm {inst}\n.model mm {m} {mp}"
SWCTL = ("noise v(x) V1 lin 1 1k 1k\nsetplot noise1\nprint onoise_spectrum")

rc, out, osdi = compile_file("nsw.va")
check("[4] nsw.va compiles", rc == 0, out.strip().splitlines()[-1] if rc else "")

if rc == 0:
    def sw_noise(model, mp, inst, tag):
        sim = run(SWDECK.format(m=model, mp=mp, inst=inst), SWCTL, tag, osdi)
        return num(sim, "onoise_spectrum")

    # the flow arm, against the plain branch, at m = 1 and m = 9
    for mult, want, why in [
        ("", 5e-4, "m=1"),
        ("m=9", 3e-4, "m=9 -- LRM 6.3.6 multiplies the noise POWER, so the "
                      "density goes as sqrt(m); this read 2.70e-3 (m^1.5)"),
    ]:
        plain = sw_noise("nplain", "", mult, f"pl{mult}")
        swf = sw_noise("nswf", "sw=1", mult, f"swf{mult}")
        check(f"[4] flow arm equals the plain branch at {why}",
              close(plain, want, 1e-9) and close(swf, want, 1e-9),
              f"plain={plain} switch={swf}")

    # the potential arm -- the noise-only contribution that used to vanish
    # when its arm was lowered second
    p_second = sw_noise("nswf", "sw=0", "", "pot2nd")
    p_first = sw_noise("nswp", "sw=1", "", "pot1st")
    check("[4] a noise-only potential arm survives whichever arm is written "
          "first (it was dropped when lowered second: 4.07e-9, the load alone)",
          close(p_second, 1e-6, 1e-9) and close(p_first, 1e-6, 1e-9),
          f"flow-first={p_second} potential-first={p_first}")
    check("[4] ...and the potential arm still divides by sqrt(m) (6.3.6)",
          close(sw_noise("nswf", "sw=0", "m=9", "pot9"), 1e-6 / 3, 1e-9),
          f"{sw_noise('nswf', 'sw=0', 'm=9', 'pot9b')}")

    # ac_stim rides the same injection point and had the same extra m
    print("\nac_stim on a switch branch (LRM 4.6.3 + 6.3.6):")
    ACCTL = "ac lin 1 1k 1k\nprint vm(x)"
    def sw_ac(model, mp, inst, tag):
        body = "V1 a 0 dc 0 ac 0\nR1 a x 1k\nN1 x 0 mm {i}\n.model mm {m} {p}".format(
            m=model, p=mp, i=inst)
        return num(run(body, ACCTL, tag, osdi), "vm(x)")

    for mult, want in [("", 0.5), ("m=9", 0.9)]:
        plain = sw_ac("nplainac", "", mult, f"acpl{mult}")
        swa = sw_ac("nswac", "sw=0", mult, f"acsw{mult}")
        check(f"[4] a current ac_stim arm equals the plain branch at "
              f"{mult or 'm=1'} (it read 8.1 V at m=9)",
              close(plain, want, 1e-9) and close(swa, want, 1e-9),
              f"plain={plain} switch={swa}")
    check("[4] a voltage ac_stim arm stays mfactor-invariant (E-51)",
          close(sw_ac("nswac", "sw=1", "", "acv1"), 1.0, 1e-9)
          and close(sw_ac("nswac", "sw=1", "m=9", "acv9"), 1.0, 1e-9),
          f"{sw_ac('nswac', 'sw=1', 'm=9', 'acv9b')}")

print(f"\n{'ALL PASS' if checks == passed else 'FAILURES'}: {passed}/{checks} passed")
sys.exit(0 if checks == passed else 1)
