#!/usr/bin/env python3
"""compile_all.py -- compile every .va file under VA_TEST/ with the committed
openvaf-r and regenerate compile_report.md.

The corpus is the public VA-Models collection (VA-Models-main/): the
industry-standard compact models (BSIM4/6/BULK/CMG/IMG/SOI, PSP 102/103/104,
PSP-HV, HiCUM L0/L2, MEXTRAM 504/505, VBIC, EKV 2.6/3, ASM-HEMT, EPFL-HEMT,
Angelov, MVSG, diode_cmc, r2/r3_cmc, L-UTSOI, MOSVAR, IGBT, ...) plus the
playground examples. All standalone models are expected to compile (exit 1
if any fails).

Files that are `include`d by another .va file in the tree are include
FRAGMENTS (macro bodies, parameter lists, module-body pieces) -- they are not
standalone modules and are reported separately; their failures don't count.

Usage:  python3 VA_TEST/compile_all.py
"""
import os
import re
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "examples"))
from _setup import VAF as OPENVAF

REPORT = os.path.join(HERE, "compile_report.md")

va_files = []
for dirpath, _, files in os.walk(HERE):
    for f in sorted(files):
        if f.endswith(".va"):
            va_files.append(os.path.join(dirpath, f))
va_files.sort()

# files `include`d by others in the tree are fragments, not standalone models
inc_re = re.compile(r'`include\s+"([^"]+)"')
included = set()
for path in va_files:
    text = open(path, encoding="utf-8", errors="replace").read()
    for m in inc_re.finditer(text):
        name = os.path.basename(m.group(1))
        if name.endswith(".va"):
            included.add(name)

results = []
with tempfile.TemporaryDirectory() as outdir:
    for path in va_files:
        rel = os.path.relpath(path, HERE)
        is_include = os.path.basename(path) in included
        out = os.path.join(outdir, rel.replace(os.sep, "__") + ".osdi")
        t0 = time.time()
        try:
            p = subprocess.run([OPENVAF, path, "-o", out],
                               capture_output=True, text=True, timeout=300)
            dt = time.time() - t0
            ok = p.returncode == 0 and os.path.exists(out)
            err = (p.stderr or p.stdout).strip()
        except subprocess.TimeoutExpired:
            dt, ok, err = time.time() - t0, False, "TIMEOUT after 300s"
        first_err = ""
        if not ok:
            for line in err.splitlines():
                if "error" in line.strip()[:30].lower():
                    first_err = line.strip()
                    break
            if not first_err:
                first_err = err.splitlines()[0].strip() if err else "(no output)"
        results.append((rel, is_include, ok, dt, first_err, err))
        print(f"{'PASS' if ok else 'FAIL'} {dt:6.1f}s  {rel}"
              + ("" if ok else f"  -- {first_err[:100]}"))

main_results = [r for r in results if not r[1]]
inc_results = [r for r in results if r[1]]
np_, nf = sum(r[2] for r in main_results), sum(not r[2] for r in main_results)
ip, if_ = sum(r[2] for r in inc_results), sum(not r[2] for r in inc_results)

with open(REPORT, "w") as fh:
    fh.write("# VA_TEST compile report — openvaf-r\n\n")
    fh.write(f"Generated by `compile_all.py` · Compiler: the committed `openvaf-r` "
             f"(OpenVAF-Reloaded) · Files: {len(results)} `.va`\n\n")
    fh.write(f"**Standalone models: {np_}/{len(main_results)} compile.** "
             f"Include fragments (files `` `include ``d by other `.va` files, "
             f"not meant to compile standalone): {ip}/{len(inc_results)} compile anyway.\n\n")
    fh.write(f"## Standalone models ({np_} pass / {nf} fail)\n\n")
    fh.write("| File | Result | Time (s) | Error (first line) |\n|---|---|---|---|\n")
    for rel, _, ok, dt, first_err, _ in main_results:
        e = first_err.replace("|", "\\|") if not ok else ""
        fh.write(f"| `{rel}` | {'✅ PASS' if ok else '❌ FAIL'} | {dt:.1f} | {e} |\n")
    fh.write(f"\n## Include fragments ({ip} pass / {if_} fail)\n\n")
    fh.write("These files are pulled in via `` `include `` by the models above; "
             "standalone compilation is not expected to succeed for all of them.\n\n")
    fh.write("| File | Result | Time (s) | Error (first line) |\n|---|---|---|---|\n")
    for rel, _, ok, dt, first_err, _ in inc_results:
        e = first_err.replace("|", "\\|") if not ok else ""
        fh.write(f"| `{rel}` | {'✅ PASS' if ok else '❌ FAIL'} | {dt:.1f} | {e} |\n")
    fails = [r for r in main_results if not r[2]]
    if fails:
        fh.write("\n## Failure details (standalone models)\n\n")
        for rel, _, ok, dt, first_err, err in fails:
            fh.write(f"### `{rel}`\n\n```\n")
            fh.write("\n".join(err.splitlines()[:30]))
            fh.write("\n```\n\n")

print("\nreport written:", os.path.relpath(REPORT, ROOT))
print(f"standalone: {np_} pass / {nf} fail; includes: {ip} pass / {if_} fail")
print("ALL PASS" if nf == 0 else "SOME STANDALONE MODELS FAILED")
sys.exit(0 if nf == 0 else 1)
